name: Publish Snapshots

on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ main ]
    types: [ completed ]

permissions:
  contents: read
  packages: write

jobs:
  publish-snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Update repository URL in pom.xml
        shell: bash
        run: |
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          sed -i "s|OWNER|$REPO_OWNER|g" pom.xml

      - name: Verify snapshot version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $VERSION != *-SNAPSHOT ]]; then
            echo "Error: Version $VERSION is not a SNAPSHOT version"
            exit 1
          fi
          echo "Publishing snapshot version: $VERSION"

      - name: Publish Package Snapshot
        run: mvn -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}