name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 17
          - os: ubuntu-latest
            jdk: 21
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin

      - name: Run tests
        run: mvn -q clean verify -B